### PR TITLE
Fix Webpack Local Dev Server

### PR DESCRIPTION
**Pull request by BearHanded**
### Description

Following the webpack dev server v3 -> v4 guide [here](https://github.com/webpack/webpack-dev-server/blob/master/migration-v4.md).

- Config changes for new property names and some general reshuffling
- Use new start command
- Move away from deprecated handlers for middleware setup
- Remove hot loading plugin from general config, `hot: true` handles that in our dev config.

The update should get us back up for local dev. 

**Known Issues**
- ~~Error handling overlays do not work~~ This never worked.
- ~~hot loading works with a manual refresh but does not automatically reload the page. This previously worked with css.~~ Now works

### Related ticket(s)

N/A

---
### How to test

Run local, try to break it, look for oddities

### Important updates

---
### Author checklist

- [ ] I have performed a self-review of my code
- [ ] I have added [thorough](https://shorturl.at/aejkF) tests, if necessary
- [ ] I have updated relevant documentation, if necessary
---

_convert to a different template: [test → val](?expand=1&template=test-to-val-deployment.md)_ | _[val → prod](?expand=1&template=val-to-prod-deployment.md)_

### CODE REVIEW

**Review by ailZhou — APPROVED** [review]
lgtm! seds work for me again locally!

**Comment by benmartin-coforma** [comment]
Maybe we'll just call it "warm" loading then?

**Review by benmartin-coforma — APPROVED** [review]
I think a proper review would involve re-doing your work here, but I already trust it.

**Review by ailZhou — APPROVED** [review]
seds out here trying to make me a liar, suddenly worked in a screenshare with Brendan.

**Review by berryd — APPROVED** [review]

**Review by karla-vm — APPROVED** [review]

**Pull request merged**
